packages:
  - "packages/*"
  - "apps/*"

allowBuilds:
  '@biomejs/biome': true
  better-sqlite3: true
  esbuild: true

catalog:
  "@biomejs/biome": "1.9.4"
  "@commitlint/cli": "19.5.0"
  "@commitlint/config-conventional": "19.5.0"
  "@types/better-sqlite3": "7.6.12"
  "@types/node": "22.9.0"
  "@types/react": "18.3.12"
  "@types/react-dom": "18.3.1"
  "better-sqlite3": "11.5.0"
  "husky": "9.1.6"
  "license-checker": "25.0.1"
  "lint-staged": "15.2.10"
  "react": "18.3.1"
  "react-dom": "18.3.1"
  "tsup": "8.3.5"
  "turbo": "2.2.3"
  "typescript": "5.6.3"
  "vitest": "2.1.5"
  "zod": "3.23.8"
